services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sb-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      # Override DB/Redis host to match service names in Docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mmdb
      SPRING_DATASOURCE_USERNAME: mmdbuser
      SPRING_DATASOURCE_PASSWORD: 00000000
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: mmdb
      MYSQL_USER: mmdbuser
      MYSQL_PASSWORD: 00000000
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ${HOME}/DockerFileShare/db.sql:/docker-entrypoint-initdb.d/db.sql:ro

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
