version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "1234:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/ssl:/home/user/ssl:ro
      - ./validation:/home/user/validation:ro
    depends_on:
      - frontend
    restart: always

  frontend:
    build:
      context: ./sbp-client-nuxt
    restart: always

  backend:
    build:
      context: .
    depends_on:
      - postgres
    restart: always

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_USER: mmdbuser
      POSTGRES_PASSWORD: 00000000
      POSTGRES_DB: mmdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

volumes:
  pgdata:
