name: cicd

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (Optional, only needed if using some files locally)
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa.pem
        chmod 600 ~/.ssh/id_rsa.pem

    - name: Add to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts


    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: ./mvnw clean install

    - name: Copy JAR to VM
      run: |
        scp -i ~/.ssh/id_rsa.pem -o StrictHostKeyChecking=no app/target/app*.jar ec2-user@${{ secrets.HOST }}:~/app.jar
